### ISSUE TITLE
Question : Does this support piping?

### ISSUE THREAD

**Issue by rnbokade** [fsphil/ssdv#2]
I mean it will be really great if we can pip live stream of data directly into the ssdv decoder. E.g. if say I am sending SSDV sans-FEC on AFSK1200 wrapped with ax 25. Then ly decode chani could be 
rtl_fm | multimon-ng -a AFSK1200 | SSDV - d output.jpeg.
Even better if some terminal based image viewer like FEH could be integrated in the chain somehow although that is far fetched.
We are taking inspiration some of your master piece code that resides in Hadie repo, for generating ssdv frames in our upcoming satellite. Would be great if some simple chain as above could be achievable.

**Comment by fsphil** [comment]
The `ssdv` program currently only processes a single image a time, so it's not well suited for piping. You *can* pipe packets into it provided they're all for a single image, and they're send in the correct order (packet_id ascending).

> code that resides in Hadie repo

Be aware that that is very old code and hasn't been updated in a long time. There've been a few bugs found and fixed in this repo that haven't been ported back into hadie. You'd be better to use the code from this repo, and remove all the parts you don't need for decoding.
